name: imager
description: Flutter package to conveniently work with image widgets which comes from network, local, file and memory
version: 0.0.1
homepage: https://github.com/javaherisaber/imager.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
